services:
  frontend:
    image: 0noder4/next-pi-calc:alfa
    container_name: ${PROJECT_SLUG}_frontend
    build:
      context: ./
      target: ${NODE_ENV}
      args:
        NODE_ENV: ${NODE_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${PORT-80}:3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    networks:
      - internal

networks:
  internal:
